# Generated by Django 3.2.7 on 2021-10-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('seq', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, verbose_name='user_email')),
                ('nickname', models.CharField(max_length=30, verbose_name='user_name')),
            ],
        ),
    ]
