# Generated by Django 3.2.7 on 2021-10-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='kakao_id',
            field=models.CharField(default='0', max_length=30, verbose_name='user_id'),
        ),
    ]
