# Generated by Django 3.2.7 on 2021-10-06 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211006_0926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='content',
            new_name='card',
        ),
    ]
