# Generated by Django 3.2.7 on 2021-10-07 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='meta',
            field=models.TextField(blank=True),
        ),
    ]
